### ISSUE TITLE
Can you explain the logic that validates the user can save permission?

### ISSUE THREAD

**Issue by chromeo** [tutsplus/tutsplus-post-notice#1]
I followed your great tutorial all the way thru, and understand everything except for the part where you validated the ability of the user to save the post. Specifically, in lesson 4.3, you used this code inside the `user_can_save()` function:

```
$is_autosave = wp_is_post_autosave( $post_id );
$is_revision = wp_is_post_revision( $post_id );

return ! ( $is_autosave || $is_revision );
```

You also said, "the return statement checks to see if this is an autosave or a revision, and if NOT it will  return true. This means the user has permission to save".

I'm lost on the logic here, and I googled it extensively. So the question I hope you can answer:

**How does a FALSE value for those two variables prove the user has permission to save?**

Again, great tutorial, I just need a little guidance on this aspect. Thanks Tom.

**Comment by tommcfarlin** [comment]
Sure thing!

The first two function calls, that is, those that are made to `wp_is_post_autosave` and `wp_is_post_revision` determine if the post is being automatically saved by WordPress or if the post that's being viewed is one of the revisions to the actual post.

We use this to make sure that it's the user editing the most recently used version of the post rather than WordPress automatically saving an update to the post or the user working on a previous version of the post.

Feel free to re-open this issue if it doesn't make sense!

**Comment by chromeo** [comment]
Okay, that kinda makes sense. When you said "...this means the user has
permission...", I interpreted that as something involving user
capabilities, like there was a call being made to current_user_can()
whenever these two functions are invoked.

It sounds like what you're saying here is that if one of those functions
returns a true value, then that prevents the custom function we created
from saving the post data. We are not checking permission at at user
capability level, but granting or denying permission within this function
to proceed without interfering with autosave, or revising the current
version.

I assume then that the later application of nonces takes care of the user
capability stuff.

Thanks for the reply Tom.

Gary Darling

**Comment by tommcfarlin** [comment]
> I assume then that the later application of nonces takes care of the user capability
> stuff.

Yep - this particular method is outside the usual roles and capabilities
discussion.

It's just making sure that when the serialization is happening, that the
values are being saved based on the user taking an action (versus WordPress
doing something in the background).

-- Tom
